language: java

services:
  - docker
  - maven

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:

  # Build front
  - cd front
  - npm install
  - npm run build
  
  # Run front tests
  - npm run test-ci

  # Copy new generated resources on back static
  - cd ../back
  - mkdir -p "src/main/resources/static/" && cp -r ../front/dist/front/* src/main/resources/static/

  # Build back (create .jar and run tests)
  - mvn package

  # Build docker image
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mkdir -p "../docker/build/" && cp -r target/back-0.0.1-SNAPSHOT.jar ../docker/build/; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cd ../docker; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker build -t "$DOCKER_USERNAME"/santatecla .; fi

  # Push to Docker Hub
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push "$DOCKER_USERNAME"/santatecla; fi
