language: java

services:
  - docker
  - maven

addons:
  sonarcloud:
    organization: "jesusborrero"
    token:
      secure: "YJ17dH7Pb57A/xh32HahcY85px8RezLZm5Kse/AFH1B542gyLhugFTwo5LpJ1h+jkIClwc5zhJKIYeBUaKOz3ePlyJniLjRKvRj1/ZBi8Gs4t4wyc78jrWp/wOiJFXIIeNUkY8F2xKkR7xV7WBZ0scO8HOEw2v0ouUDV35828tGnADyFZefs0kfcwSYFYbNdEdEFcGLmc5sg4/LtSUoR1kPMFZPN0PYZbognack5Sp/VyNEC0UgFPNVLXyIZ4g1jmH/QX5VcicJr/KfjyDUjraqtJezzh0uHZBeimrBLNa7FFcLGPegYpoEqdCjFs+og/Wij8z8j4m+NGVewvZ41xWwLmJfBrrc9STQ9H8fCl2V5Bw98UYc8IXjCR79guJHgwiUKEoY08RaD8hqCJsKa0cxv/lxsueqrje+//YOAZNFtVrD8JDOoawjRT0ZF8kMOC79zlLdrdAMDflU4j0c5FXCCHCAEtKN3gzKpIOaMYeUHJJ7tPhGkdTWlK43+VUQCLz8gYUINxZ8ZdKuHbxosD6UfP3EKooGOn3KFFfeib32+ZhC1uDZQo6MNw07IiYICBJexji2gMbfDyFX6b7WP12Aja0HGswz1s6plQLXK81BPH4Nmtatz+rrjGl0bYIWIIBHQ/a1iFu+p4gQHA67Jne70A+ByDWvmSzoaHckfNbM="

script:

  # Build angular app
  - cd front
  - docker run --rm --name angular-cli -v ${PWD}:/angular -w /angular node /bin/bash -c "npm install; npm run build"

  # Copy new generated resources on back static
  - cd ../back
  - mkdir -p "src/main/resources/static/" && cp -r ../front/dist/front/* src/main/resources/static/

  # Create jar
  - mvn package

  # Build docker image
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mkdir -p "../docker/build/" && cp -r target/back-0.0.1-SNAPSHOT.jar ../docker/build/; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cd ../docker; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker build -t "$DOCKER_USERNAME"/santatecla .; fi

  # Push to Docker Hub
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push "$DOCKER_USERNAME"/santatecla; fi

  # Start sonar scanner
  - sonar-scanner

