travis env set DOCKER_USERNAME sigma98
travis env set DOCKER_PASSWORD santatecla

os: windows

services:
  - docker

script:
  - cd docker
  - powershell -File run.ps1
  - if [ "$BRANCH" = "master" ]; then  docker build -t sigma98/santatecla
  - if [ "$BRANCH" = "master" ]; then  docker push -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" sigma98/santatecla