language: java

env:
  - CHROME_BIN=chromium-browser
  
services:
  - docker
  - maven

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:

  # Build angular app
  - cd front
  - docker run --rm --name angular-cli -v ${PWD}:/angular -w /angular node /bin/bash -c "npm install; npm run build"
  - docker run --rm --name angular-cli -v ${PWD}:/angular -w /angular node /bin/bash -c "npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
  - docker run --rm --name angular-cli -v ${PWD}:/angular -w /angular node /bin/bash -c "npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js"

  # Copy new generated resources on back static
  - cd ../back
  - mkdir -p "src/main/resources/static/" && cp -r ../front/dist/front/* src/main/resources/static/

  # Create jar
  - mvn package

  # Build docker image
  - if [ "$TRAVIS_BRANCH" = "master" ]; then mkdir -p "../docker/build/" && cp -r target/back-0.0.1-SNAPSHOT.jar ../docker/build/; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then cd ../docker; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker build -t "$DOCKER_USERNAME"/santatecla .; fi

  # Push to Docker Hub
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push "$DOCKER_USERNAME"/santatecla; fi
