language: c

  travis env set DOCKER_USERNAME sigma98
  travis env set DOCKER_PASSWORD santatecla

os: windows

services:
  - docker

before_install:
  - docker run --rm --name angular-cli -v ${PWD}:/angular -w /angular node /bin/bash -c "npm install; npm run build"

script:
  - cd ../back

    # Copy new generated resources on back static
  - PowerShell -Command "xcopy /Y /s ..\front\dist\front\* src\main\resources\static\"

    # Create jar
  - docker run -it --rm -v ${PWD}:/usr/src/project -w /usr/src/project maven:alpine mvn -DskipTests package
  - PowerShell -Command "xcopy /Y target\back-0.0.1-SNAPSHOT.jar ..\docker\build\"

  - if [ "$BRANCH" = "master" ]; then  docker build -t sigma98/santatecla
  - if [ "$BRANCH" = "master" ]; then  docker push -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" sigma98/santatecla