language: java

services:
  - docker
  - maven

addons:
  sonarcloud:
    projectKey: JesusBorrero_santatecla-pruebas
    organization: jesusborrero
    login: YJ17dH7Pb57A/xh32HahcY85px8RezLZm5Kse/AFH1B542gyLhugFTwo5LpJ1h+jkIClwc5zhJKIYeBUaKOz3ePlyJniLjRKvRj1/ZBi8Gs4t4wyc78jrWp/wOiJFXIIeNUkY8F2xKkR7xV7WBZ0scO8HOEw2v0ouUDV35828tGnADyFZefs0kfcwSYFYbNdEdEFcGLmc5sg4/LtSUoR1kPMFZPN0PYZbognack5Sp/VyNEC0UgFPNVLXyIZ4g1jmH/QX5VcicJr/KfjyDUjraqtJezzh0uHZBeimrBLNa7FFcLGPegYpoEqdCjFs+og/Wij8z8j4m+NGVewvZ41xWwLmJfBrrc9STQ9H8fCl2V5Bw98UYc8IXjCR79guJHgwiUKEoY08RaD8hqCJsKa0cxv/lxsueqrje+//YOAZNFtVrD8JDOoawjRT0ZF8kMOC79zlLdrdAMDflU4j0c5FXCCHCAEtKN3gzKpIOaMYeUHJJ7tPhGkdTWlK43+VUQCLz8gYUINxZ8ZdKuHbxosD6UfP3EKooGOn3KFFfeib32+ZhC1uDZQo6MNw07IiYICBJexji2gMbfDyFX6b7WP12Aja0HGswz1s6plQLXK81BPH4Nmtatz+rrjGl0bYIWIIBHQ/a1iFu+p4gQHA67Jne70A+ByDWvmSzoaHckfNbM=

script:
  # Start sonar scanner
  # Prueba
  - sonar-scanner
